import org.kagelabs.hydrogen.stl.io

print "<html>"
print "  <head>"
print "    <title> Hello, World </title>"
print "  </head>"
print "  <body>"
print "    <p> this page was generated by hydrogen </p>"
print "  </body>"
print "</html>"


