import org.kagelabs.hydrogen.stl.io
import org.kagelabs.hydrogen.stl.sys

io.print "<html>"
io.print "  <head>"
io.print "    <title> Hydrogen test </title>"
io.print "  </head>"
io.print "  <body>"
io.print "    <p> this page was generated by hydrogen </p>"
io.write "    <code>page generated "
$date % sys.xcall "date"
io.write $date 
io.print "</code>"
io.print "  </body>"
io.print "</html>"


